### ISSUE TITLE
Villager API 1.26.7.1 crashes on Minecraft 26.3 Fabric – MapDecorationType NoSuchMethodError

### ISSUE THREAD

**Issue by dolcegabbana1** [frikinjay/villagerapi#6]
Hello,

I am having a startup crash with Villager API 1.26.7.1 on a Minecraft 26.3 Fabric server.

According to the Modrinth page, Villager API 1.26.7.1 supports Minecraft 26.3 and Fabric/Quilt, so I believe I am using the intended version. More Villagers: Re-employed 1.26.7.1 also lists Minecraft 26.3 as supported.

However, the server crashes during initialization with a NoSuchMethodError inside Villager API.

Environment
Minecraft: 26.3
Mod loader: Fabric
Fabric Loader: 0.19.5
Java: 25
Villager API: 1.26.7.1
More Villagers: Re-employed: 1.26.7.1
Environment: Dedicated server

The exact Fabric file I am using is:

Villager-API-26.1.x-fabric-1.26.7.1.jar

This is the Fabric build listed by CurseForge for the 1.26.7.1 release.

Crash

The server reaches the Villager API initialization and then fails with:

Failed to start the minecraft server

java.lang.RuntimeException: Could not execute entrypoint stage 'main'
due to errors, provided by 'villagerapi' at
'com.frikinjay.villagerapi.fabric.VillagerAPIFabric'!

Caused by: java.lang.NoSuchMethodError:
'void net.minecraft.world.level.saveddata.maps.MapDecorationType.<init>(
net.minecraft.resources.Identifier,
boolean,
int,
boolean,
boolean
)'

The relevant stack trace is:

at com.frikinjay.villagerapi.common.map.VAPIMapDecorations.lambda$registerFromPack$0
at com.frikinjay.villagerapi.common.platform.CommonPlatformHelperImpl.registerMapDecorationType
at com.frikinjay.villagerapi.common.map.VAPIMapDecorations.registerFromPack
at com.frikinjay.villagerapi.common.pack.VillagerPackRegistry.registerMapDecorationTypes
at com.frikinjay.villagerapi.common.pack.PackInitializationOrchestrator.registerMapDecorationTypes
at com.frikinjay.villagerapi.fabric.VillagerAPIFabric.onInitialize

So the crash appears to happen when Villager API attempts to register map decoration types from a villager pack.

Additional information

The server itself works correctly on Minecraft 26.3 with Fabric when Villager API and More Villagers are removed.

With the mods installed, Fabric successfully detects:

villagerapi 1.26.7.1
morevillagers 1.26.7.1

The More Villagers pack also passes validation immediately before the crash.

The important part is that the failure is not a missing dependency or a Fabric entrypoint failure. Villager API itself reaches its initialization code and then attempts to call a MapDecorationType constructor which does not exist in the Minecraft 26.3 runtime.

This makes me suspect that the 1.26.7.1 Fabric build may have been compiled against a different Minecraft 26.x mapping/API state than the final 26.3 release, despite being marked as compatible with 26.3.

Expected behavior

Villager API 1.26.7.1 should initialize successfully on a Minecraft 26.3 Fabric server and register the villager pack's map decorations without crashing.

Actual behavior

The dedicated server crashes during startup with:

NoSuchMethodError:
MapDecorationType.<init>(Identifier, boolean, int, boolean, boolean)
Reproduction
Create a clean Minecraft 26.3 Fabric server.
Use Fabric Loader 0.19.5.
Use Java 25.
Install:
Villager API 1.26.7.1
More Villagers: Re-employed 1.26.7.1
Start the server.
The server crashes during Villager API initialization.
Request

Could you please check the MapDecorationType registration code in VAPIMapDecorations against the final Minecraft 26.3 API/mappings?

In particular, this call appears to be incompatible with the MapDecorationType constructor available at runtime:

MapDecorationType(
    Identifier,
    boolean,
    int,
    boolean,
    boolean
)

If 26.3 changed the constructor/API, the Fabric 1.26.7.1 build may need to be rebuilt or the map decoration registration code updated for the final 26.3 API.

Thanks!

**Comment by frikinjay** [comment]
Fixed in 1.26.9.1
